server {
    listen 80;
    server_name localhost;

    # 1. Vue Frontend Dosyalarının Dağıtımı
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Vue Router (History Mode) sayfa yenileme hatalarını önlemek için:
        try_files $uri $uri/ /index.html;
    }

    # 2. API İsteklerini Arka Plandaki C# Konteynerine Yönlendirme
    # Tarayıcıdan gelen "/api/..." isteklerini prj-network ağındaki stok_api'ye paslar.
    location /api/ {
        resolver 127.0.0.11 valid=30s;
        set $upstream http://stok_api:8080;
        proxy_pass $upstream;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'keep-alive';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}